version: '3'

tasks:
  default:
    desc: List available commands.
    cmds:
      - task --list
      - echo ""
      - echo First time? Run [ task build ] to build the project image.
    silent: true

  build:
    desc: Build the project image.
    cmds:
      - yarn install
      - echo ""
      - docker-compose build
      - echo ""
      - echo "You are ready to start the project, run [ task start ] to start."
    silent: true

  start:
    desc: Start the project container.
    cmds:
      - docker-compose up -d
      - echo ""
      - echo The app is running on http://localhost:3000/.
    silent: true

  stop:
    desc: Stop the project container.
    cmds:
      - docker-compose stop
      - echo ""
      - echo The project container is stopped.
    silent: true

  lint:
    desc: Run the project codestyle check.
    cmds:
      - echo Starting app codestyle check..
      - docker-compose exec app sh -c "yarn lint"
    silent: true

  update:
    desc: Update all dependencies.
    cmds:
      - echo Updating dependencies..
      - yarn upgrade-interactive --latest

  reset:
    desc: Reset the project container, volumes & local dependencies.
    cmds:
      - echo Removing node_modules folder..
      - sudo rm -rf node_modules
      - echo node_modules folder removed.
      - echo ""
      - docker-compose down -v
    silent: true